<a href="https://colab.research.google.com/github/KimEun-Bi/etc../blob/master/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%9D%91%EC%9A%A9_1%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **print()**

1.   항목 추가
2.   항목 추가



In [ ]:
######주석

오늘 배울 기초 문법

ㅇㅇㅇㅇㅇㅇㅇㅇ

In [ ]:
#코드 셀 추가 가능해요

In [ ]:
######주석

In [ ]:
#print() 
###은 주석이예요
print("Hello, World!")

In [ ]:
#미션1. 이름으로 삼행시 짓기


변수: **자료형**의 값을 저장하는 공간

In [ ]:
#미션2. 여러분의 변수를 만들어봅시다. my_var라는 이름의 변수를 만들고, print로 출력해서 확인해봅시다


이론수업 PPT로!

# **자료형(연산)**

자료형(숫자형)

In [ ]:
#자료형을 알아보자!

type(10)

In [ ]:
#자료형을 알아보자!
type(3.14)

연산

In [ ]:
#연산
a = 10
b = 2

In [ ]:
# 더하기
a + b

In [ ]:
# 빼기
a - b

In [ ]:
# 곱하기
a * b

In [ ]:
# 제곱
a ** b

In [ ]:
# 나누기
a / b

In [ ]:
# 나누기 나머지
a%b

In [ ]:
# 나누기 : 몫
a // b

자료형(문자형)

In [ ]:
#자료형을 알아보자!
type('Hello word')

In [ ]:
print("안녕"+"하세요")

In [ ]:
print("안녕"*3)

In [ ]:
#미션3.0
## 숫자 50과 숫자 50 더해서 출력하기


In [ ]:
#미션3.1
## 문자열 50과 문자열 50 더해서 출력하기


In [ ]:
#미션3.1
## 리스트 50과 리스트 50 더해서 출력하기


In [ ]:
#미션3.3 거꾸로 계산기
# //을 이용해서 변수 intdiv에 4를 넢은 수식을 작성해봅니다. 

#%을 이용하여 변수 modular에 1을 넣는 수식을 작성해봅니다

#**을 이용해서 변수 expo에 16을 넣는 수식을 작성해봅시다.

#위의 세변수를 출력해서 확인해봅시다
print(intdiv, modular, expo)



자료형(불린, 논리 자료형)

In [ ]:
# 불린(boolean)
a = 1
b = 2

In [ ]:
print(a<b)

In [ ]:
print(b<a)

In [ ]:
#자료형을 알아보자!
t, f = True, False
type(t)

In [ ]:
#미션4. 비교연산자로 명제 만들기

## == 혹은 != 연산자를 이용해서 True인 명제를 ans1에 넣어봅시다.


## > 혹은 < 연산자를 이용해서 False인 명제를 ans2에 넣어봅시다


##위의 변수를 출력해서 정답을 확인해봅시다. 
print(ans1, ans2)


In [ ]:
#불린의 연산(and, or, not)

ab = 3==3 and 2<5 #T
bc = 4>=6 #F
cd = not 4>5 #T

print(ab, bc, cd)

자료형(리스트)

In [ ]:
a = [1, 2, 3, 4]
type(a)

In [ ]:
#리스트는 자르고 찾는 것이 가능해요

v =['화이자' , '모더나' , 'AZ' , '얀센' ]
type(v)

In [ ]:
##인덱싱(indexing)
v[1]

In [ ]:
v[0]

In [ ]:
v[-1]

In [ ]:

v =['화이자' , '모더나' , 'AZ' , '얀센' ]

In [ ]:
## slicing (슬라이싱)
v[1:]

In [ ]:
v[:]

In [ ]:
v[:-1]

In [ ]:
v =['화이자' , '모더나' , 'AZ' , '얀센' ]

In [ ]:
v[2] = 'AA' # 수정
v

In [ ]:
v.append('BB') #추가 : 자료를 리스트 마지막 원소 뒤에 추가(오직 한개의 자료만 넣을 수 있다.)
v

In [ ]:
v.insert(2,3) #list.insert(i,d): 인덱스 i(위치)에 자료d(값)를 추가(오직 한개의 자료만 넣을 수있다())
v

In [ ]:
v =['화이자' , '모더나' , 'AZ' , '얀센' ]

In [ ]:
v.sort() #정렬: 숫자형은 오름차순, 문자열은 사전순
v

In [ ]:
v.reverse() #거꾸로
v

In [ ]:
v.index('화이자') #bb는 어디있나요

In [ ]:
v.remove('화이자') #제거
v

자료형(튜플)

In [ ]:
#  튜플

type(('화이자' , '모더나' , '아스트라제네카' , '얀센'))

Set (집합)

In [ ]:
# Set - 중복이 되면 안되는 경우

user_set_a = {"user_1", "user_2", "user_3", "user_1"}
user_set_b = {"user_2", "user_3"}

print(user_set_a)

In [ ]:
type(user_set_a)

In [ ]:
# 교집합
user_set_a & user_set_b

In [ ]:
# 합집합
user_set_a | user_set_b 

In [ ]:
# 차집합
user_set_a - user_set_b


Dict (딕셔너리)

In [ ]:
# dictionary key와 value값으로 이뤄짐

dic_1 = { '제조사' : '화이자/바이오엔텍' , 
         '플랫폼' : 'mRNA 백신 (핵산 백신)' , 
         '연령' : '만 16세 이상' }

In [ ]:
type(dic_1)

In [ ]:
print(dic_1)

In [ ]:
dic_1

input() 형변환

In [ ]:
#'123' 문자열을 숫자로 바꾸기
int('123')

In [ ]:
#미션5. 2배로 적금만들기

##변수 money에 input을 이용해서 입력을 받아봅시다.


##money를 int형으로 변환해서, 다시 money에 넣어줍니다.


##money를 2배로 불려서 print로 출력을 해봅시다


시퀀스 정리하기

In [ ]:
#미션6. 기차놀이
#현재 기차에는 3명의 승객이 탑승하고 있습니다. 
train = ['금비','은비','동비']

#서울역에 정차했습니다.
##승객 '까비'를 맨 뒷칸에 태우세요

print('서울역 도착.//',train)

#대전역에 정차했습니다.
##1등석 승객 '선녀'가 탑습했습니다. 맨앞에 태우세요

print('대전역 도착.//', train)

#동대구역에 정차했습니다.
##승객 '은비'를 하차시켜주세요

print('대구역 도착.//', train)

#마지막 역인 부산에 정차했습니다.
##원할한 하차를 위해 손님들의 자리를 사전순으로 다시 지정해주세요

print('부산역 도착.//', train)

이론수업 ppt로!

if ... else
* a == b
* a != b #같지않다
* a < b
* a <= b
* a > b
* a >= b

In [ ]:
a = 42
b = 100
if b > a:
  print("b 가 a보다 큼")

In [ ]:
# Elif - 그렇지않다면
a = 41
b = 41
if b > a:
  print("b 가 a보다 큼")
elif a == b:
  print("a 와 b는 같음")

In [ ]:
# if .. elif .. else
a = 101
b = 100
if b > a:
  print("b 가 a보다 큼")
elif a == b:
  print("a 랑 b 는 같음")
else:
  print("a 가 b보다 큼")

In [ ]:
#응용.점심메뉴 정하기
메뉴 = '짜장면' # 먹고싶은 메뉴
중국집 = ['짜장면', '탕수육', '삼선짬뽕']
일식집 = ['초밥', '우동', '돈까스']

if 메뉴 in 중국집:
  print("중국집으로 시키자!")
elif 메뉴 in 일식집:
  print("일식집으로 시키자!")

In [ ]:
# and
a = 42
b = 100
if b > a and b < 200:
  print("b 가 a보다 크고 200보다는 작음")

In [ ]:
# or
a = 42
b = 11
if b < a or b > 10:
  print("b 가 a나 10보다 큼")

In [ ]:
#if 속의 if
a = 10
b = 100
if b > 10:
  print("b 가 10보다 큼")
  if b > a:
    print("b 가 a보다 큼")
  else:
    pass

In [ ]:
#미션6. 홀짝판별기

##input()을 이용해서 숫자(정수) 입력을 받고, 변수 num에 이를 넣어봅시다.
num = int(input())
##if-else 문을 이용해서 만약 입력받은 수가 홀수면 "(입력받은수) 홀수입니다."
##짝수면 "(입력받은수) 짝수입니다"를 출력해봅시다
if num%2 == 0:
  print(num,"짝수입니다")
else:
  print(num, "홀수입니다")




In [ ]:
#미션6. 홀짝판별기

##input()을 이용해서 숫자(정수) 입력을 받고, 변수 num에 이를 넣어봅시다.
num = int(input())
##if-else 문을 이용해서 만약 입력받은 수가 홀수면 "(입력받은수) 홀수입니다."
##짝수면 "(입력받은수) 짝수입니다"를 출력해봅시다
if num%2 == 1:
  print(num,"홀수입니다")
else:
  print(num, "짝수입니다")


In [ ]:
#미션7. 업-다운

##변수 answer에 수 1~50 중 하나를 넣어봅시다.
answer = 2

##input을 통해 숫자형으로 입력을 받아서 변수 submit에 저장해봅시다.
submit = int(input())

##if-elif-else 문으로 
###만약 answer 보다 submit이 더 크면 "정답보다 더 큰 수를 입력했습니다"
###만약 answer 보다 submit이 더 작으면 "정답보다 더 작은 수를 입력했습니다"
###만약 answer 보다 submit이 같으면 "정답!"을 출력합니다. 
if answer < submit:
  print('정답보다 더 큰 수를 입력했습니다')
elif answer == submit:
  print('정답!')
else:
  print("정답보다 더 작은 수를 입력했습니다")

In [ ]:
##변수 answer에 수 1~50 중 하나를 넣어봅시다.
answer = 2

##input을 통해 숫자형으로 입력을 받아서 변수 submit에 저장해봅시다.
submit = int(input())

##if-elif-else 문으로 
###만약 answer 보다 submit이 더 크면 "정답보다 더 큰 수를 입력했습니다"
###만약 answer 보다 submit이 더 작으면 "정답보다 더 작은 수를 입력했습니다"
###만약 answer 보다 submit이 같으면 "정답!"을 출력합니다. 
if answer < submit:
  print('정답보다 더 큰 수를 입력했습니다')
elif answer > submit:
  print('정답보다 더 작은 수를 입력했습니다')
else:
  print("정답")


이론 수업 ppt로

In [ ]:
#while
i = 1
while i<11:
    print(i)
    i=i+1

In [ ]:
#while
#미션
#while을 이용해서 "i 년째 수감중입니다."를 출력해봅시다.
#while문이 종료된 후에는, "감옥에서 석방되었습니다!"를 출력해봅시다.

j=1
while j<=10:
    print(j, "년째 수강중입니다")
    j=j+1 #j가 10년을 넘을수있도록
print("감옥에서 석방되었습니다!")

for
- 순서형 자료를 반복 실행 (iterate)

In [ ]:
fruits = ["apple", "banana", "peach", "fig"]
for x in fruits:
  print(x)

apple
banana
peach
fig


In [ ]:
for i in [1,2,3,4,5,6,7,8,9,10] :
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
# range()
for x in range(1, 11):
  print(x)

1
2
3
4
5
6
7
8
9
10


In [ ]:
a = range(1,10)
a

range(1, 10)

In [ ]:
for x in range(1, 10, 3):
  print(x)

1
4
7


In [ ]:
for x in range(100, 10, -10):
  print(x)

100
90
80
70
60
50
40
30
20


break

In [ ]:
fruits = ["apple", "banana", "peach", "fig"]
for x in fruits:
  print(x)
  if x == "peach":
    break # 구문 빠져나옴

apple
banana
peach


In [ ]:
fruits = ["apple", "banana", "peach", "fig"]
for x in fruits:
  print(x)
  if x == "peach":
    pass 

apple
banana
peach
fig


In [ ]:
#미션 19단 외우기 #변수i사용해보기
for i in range(1,20):
  print("19 *", i, "=", 19*i)


19 * 1 = 19
19 * 2 = 38
19 * 3 = 57
19 * 4 = 76
19 * 5 = 95
19 * 6 = 114
19 * 7 = 133
19 * 8 = 152
19 * 9 = 171
19 * 10 = 190
19 * 11 = 209
19 * 12 = 228
19 * 13 = 247
19 * 14 = 266
19 * 15 = 285
19 * 16 = 304
19 * 17 = 323
19 * 18 = 342
19 * 19 = 361


In [ ]:
#미션 19단 외우기 #변수i사용해보기

이론 수업 ppt로

In [ ]:
# 불러오기
import numpy as np

In [ ]:
# 버전 확인
print(np.__version__)

1.21.6


In [ ]:
# numpy array 만들기 - 1차원
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# numpy array 만들기 - 1차원
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

In [ ]:
# 2차원 numpy array 

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3차원 numpy array 
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# array 차원 확인
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [ ]:
# 더 높은 차원의 array
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(arr.ndim, '차원')

[[[[[1 2 3 4]]]]]
5 차원


In [ ]:
# 1차원 array에 접근
arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2]+arr[3])

1
2
7


In [ ]:
# 2차원 array에 접근
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('첫번째 차원의 두번째 개체 : ', arr[0, 1])

첫번째 차원의 두번째 개체 :  2


In [ ]:
# 3차원 array에 접근
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print('첫번째 array의 두번째 array의 세번째 개체 : ', arr[0, 1, 2])

첫번째 array의 두번째 array의 세번째 개체 :  6


In [ ]:
# negative indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2번째 차원의 마지막 개체 : ', arr[1, -1])

2번째 차원의 마지막 개체 :  10


In [ ]:
#쪼개기

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[1:5])
print(arr[1:5:2])
print(arr[:3])
print(arr[5:])

[2 3 4 5]
[2 4]
[1 2 3]
[ 6  7  8  9 10]


이론 수업으로

pandas

In [ ]:
import pandas as pd

In [ ]:
# pandas 버전 확인
print(pd.__version__)

1.3.5


In [ ]:
pd.Series(['코기', '허스키', '푸들'])

0     코기
1    허스키
2     푸들
dtype: object

In [ ]:
city_names = pd.Series(['서울', '부산', '대전'])
population = pd.Series([9776000, 3429000, 1531000])

pd.DataFrame({'도시': city_names, '인구':population})

도시       인구
0  서울  9776000
1  부산  3429000
2  대전  1531000

In [ ]:
# dict생성시 Series의 길이가 일치하지 않는 경우, 누락된 값은 특수 NA/NaN 값으로 채워진다.
city_names = pd.Series(['서울', '부산', '대전', '세종'])
population = pd.Series([9776000, 3429000, 1531000])

pd.DataFrame({'도시': city_names, '인구':population})

도시         인구
0  서울  9776000.0
1  부산  3429000.0
2  대전  1531000.0
3  세종        NaN

In [ ]:
# 대부분의 경우 전체 파일을 DataFrame으로 로드
# 캘리포니아 부동산 데이터를 로드해보자.
california_housing_dataframe = pd.read_csv("https://dl.google.com/mlcc/mledu-datasets/california_housing_train.csv")


In [ ]:
# dataframe에 head()를 사용하여 5개 데이터 샘플 미리보기가 가능
california_housing_dataframe.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   
5    -114.58     33.63                29.0       1387.0           236.0   
6    -114.58     33.61                25.0       2907.0           680.0   
7    -114.59     34.83                41.0        812.0           168.0   
8    -114.59     33.61                34.0       4789.0          1175.0   
9    -114.60     34.83                46.0       1497.0           309.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  
5       671.0       239.0         3.3438             74000.0  
6      1841.0       633.0         2.6768             82400.0  
7       375.0       158.0         1.7083             48500.0  
8      3134.0      1056.0         2.1782             58400.0  
9       787.0       271.0         2.1908             48100.0

In [ ]:
california_housing_dataframe.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
cities = pd.DataFrame({'도시': city_names, '인구':population})
print(type(cities['도시']))
cities['도시']

<class 'pandas.core.series.Series'>


0    서울
1    부산
2    대전
3    세종
Name: 도시, dtype: object

In [ ]:
print(type(cities['도시'][1]))
cities['도시'][1]

<class 'str'>


'부산'

In [ ]:
print(type(cities[0:2]))
cities[0:2]

<class 'pandas.core.frame.DataFrame'>


도시         인구
0  서울  9776000.0
1  부산  3429000.0

#pandsa를 활용한 전처리

In [ ]:
df = pd.read_csv('https://bit.ly/ds-korean-idol') #국내아이돌평판지수 csv파일을 다운받을 수 잇는 링크

In [ ]:
ㅗdf.head()

이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   이름       15 non-null     object 
 1   그룹       14 non-null     object 
 2   소속사      15 non-null     object 
 3   성별       15 non-null     object 
 4   생년월일     15 non-null     object 
 5   키        13 non-null     float64
 6   혈액형      15 non-null     object 
 7   브랜드평판지수  15 non-null     int64  
dtypes: float64(1), int64(1), object(6)
memory usage: 1.1+ KB


In [ ]:
#loc(열, 행)
df.loc[:, '이름'] 

0       지민
1     지드래곤
2     강다니엘
3        뷔
4       화사
5       정국
6       민현
7       소연
8        진
9      하성운
10      태연
11     차은우
12      백호
13      JR
14      슈가
Name: 이름, dtype: object

In [ ]:
df.loc[:, ['이름', '생년월일']]

이름        생년월일
0     지민  1995-10-13
1   지드래곤  1988-08-18
2   강다니엘  1996-12-10
3      뷔  1995-12-30
4     화사  1995-07-23
5     정국  1997-09-01
6     민현  1995-08-09
7     소연  1998-08-26
8      진  1992-12-04
9    하성운  1994-03-22
10    태연  1989-03-09
11   차은우  1997-03-30
12    백호  1995-07-21
13    JR  1995-06-08
14    슈가  1993-03-09

In [ ]:
df.loc[:, ['이름':'생년월일']]

SyntaxError: ignored

In [ ]:
df.iloc[:, [0, 2]]

이름      소속사
0     지민      빅히트
1   지드래곤       YG
2   강다니엘      커넥트
3      뷔      빅히트
4     화사      RBW
5     정국      빅히트
6     민현     플레디스
7     소연       큐브
8      진      빅히트
9    하성운  스타크루이엔티
10    태연       SM
11   차은우     판타지오
12    백호     플레디스
13    JR     플레디스
14    슈가      빅히트

In [ ]:
df.iloc[:, 0:2]

이름     그룹
0     지민  방탄소년단
1   지드래곤     빅뱅
2   강다니엘    NaN
3      뷔  방탄소년단
4     화사    마마무
5     정국  방탄소년단
6     민현   뉴이스트
7     소연    아이들
8      진  방탄소년단
9    하성운     핫샷
10    태연   소녀시대
11   차은우   아스트로
12    백호   뉴이스트
13    JR   뉴이스트
14    슈가  방탄소년단

In [ ]:
df.iloc[1:5, [0, 2]]

이름  소속사
1  지드래곤   YG
2  강다니엘  커넥트
3     뷔  빅히트
4    화사  RBW

이론 ppt로!

In [ ]:
df

이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442

In [ ]:
df.groupby('소속사') #groupby: 그룹으로 묶어 보기

In [ ]:
df.groupby('소속사').count()

이름  그룹  성별  생년월일  키  혈액형  브랜드평판지수
소속사                                       
RBW       1   1   1     1  1    1        1
SM        1   1   1     1  0    1        1
YG        1   1   1     1  1    1        1
빅히트       5   5   5     5  5    5        5
스타크루이엔티   1   1   1     1  1    1        1
커넥트       1   0   1     1  1    1        1
큐브        1   1   1     1  0    1        1
판타지오      1   1   1     1  1    1        1
플레디스      3   3   3     3  3    3        3

In [ ]:
#자동으로 통계가 가능한 열만 출력됩니다.
df.groupby('그룹').mean()

키       브랜드평판지수
그룹                             
뉴이스트   177.766667  3.855194e+06
마마무    162.100000  7.650928e+06
방탄소년단  176.560000  6.260169e+06
빅뱅     177.000000  9.916947e+06
소녀시대          NaN  3.918661e+06
아스트로   183.000000  3.506027e+06
아이들           NaN  4.668615e+06
핫샷     167.100000  4.036489e+06

In [ ]:
df.groupby('성별').sum()

키   브랜드평판지수
성별                  
남자  2123.2  68599637
여자   162.1  16238204

In [ ]:
df.groupby('혈액형')['키'].mean()

혈액형
A     172.966667
AB    176.500000
B     183.000000
O     177.875000
Name: 키, dtype: float64

In [ ]:
df_right = df.drop(labels='혈액형', axis=1)
df_right.head()

이름     그룹  소속사  성별        생년월일      키   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   7650928

In [ ]:
df.head()

이름     그룹  소속사  성별        생년월일      키 혈액형   브랜드평판지수
0    지민  방탄소년단  빅히트  남자  1995-10-13  173.6   A  10523260
1  지드래곤     빅뱅   YG  남자  1988-08-18  177.0   A   9916947
2  강다니엘    NaN  커넥트  남자  1996-12-10  180.0   A   8273745
3     뷔  방탄소년단  빅히트  남자  1995-12-30  178.0  AB   8073501
4    화사    마마무  RBW  여자  1995-07-23  162.1   A   7650928

In [ ]:
#concat
df2 = pd.read_csv('https://bit.ly/ds-korean-idol-2') #국내 아이돌 연봉, 가족수
df2.head()

이름    연봉  가족수
0    지민  3000    3
1  지드래곤  3500    3
2  강다니엘  3200    4
3     뷔  3050    4
4    화사  4300    3

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      15 non-null     object
 1   연봉      15 non-null     int64 
 2   가족수     15 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 488.0+ bytes


In [ ]:
pd.concat([df, df2], sort=False)
#열(row) 기준으로 합치기 concat은 list로 합쳐줍니다. 
##열기준으로 합칠때는 sort = False로 옵션을 줘서 순서가 섞이지 않도록 해요 -> 세로로 붙여준거

이름     그룹      소속사   성별        생년월일      키  혈액형     브랜드평판지수      연봉  가족수
0     지민  방탄소년단      빅히트   남자  1995-10-13  173.6    A  10523260.0     NaN  NaN
1   지드래곤     빅뱅       YG   남자  1988-08-18  177.0    A   9916947.0     NaN  NaN
2   강다니엘    NaN      커넥트   남자  1996-12-10  180.0    A   8273745.0     NaN  NaN
3      뷔  방탄소년단      빅히트   남자  1995-12-30  178.0   AB   8073501.0     NaN  NaN
4     화사    마마무      RBW   여자  1995-07-23  162.1    A   7650928.0     NaN  NaN
5     정국  방탄소년단      빅히트   남자  1997-09-01  178.0    A   5208335.0     NaN  NaN
6     민현   뉴이스트     플레디스   남자  1995-08-09  182.3    O   4989792.0     NaN  NaN
7     소연    아이들       큐브   여자  1998-08-26    NaN    B   4668615.0     NaN  NaN
8      진  방탄소년단      빅히트   남자  1992-12-04  179.2    O   4570308.0     NaN  NaN
9    하성운     핫샷  스타크루이엔티   남자  1994-03-22  167.1    A   4036489.0     NaN  NaN
10    태연   소녀시대       SM   여자  1989-03-09    NaN    A   3918661.0     NaN  NaN
11   차은우   아스트로     판타지오   남자  1997-03-30  183.0    B   3506027.0     NaN  NaN
12    백호   뉴이스트     플레디스   남자  1995-07-21  175.0   AB   3301654.0     NaN  NaN
13    JR   뉴이스트     플레디스   남자  1995-06-08  176.0    O   3274137.0     NaN  NaN
14    슈가  방탄소년단      빅히트   남자  1993-03-09  174.0    O   2925442.0     NaN  NaN
0     지민    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3000.0  3.0
1   지드래곤    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3500.0  3.0
2   강다니엘    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3200.0  4.0
3      뷔    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3050.0  4.0
4     화사    NaN      NaN  NaN         NaN    NaN  NaN         NaN  4300.0  3.0
5     정국    NaN      NaN  NaN         NaN    NaN  NaN         NaN  2900.0  5.0
6     민현    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3400.0  6.0
7     소연    NaN      NaN  NaN         NaN    NaN  NaN         NaN  4500.0  5.0
8      진    NaN      NaN  NaN         NaN    NaN  NaN         NaN  4200.0  4.0
9    하성운    NaN      NaN  NaN         NaN    NaN  NaN         NaN  4300.0  4.0
10    태연    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3700.0  3.0
11   차은우    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3850.0  5.0
12    백호    NaN      NaN  NaN         NaN    NaN  NaN         NaN  3900.0  4.0
13    JR    NaN      NaN  NaN         NaN    NaN  NaN         NaN  4100.0  3.0
14    슈가    NaN      NaN  NaN         NaN    NaN  NaN         NaN  4150.0  3.0

In [ ]:
pd.concat([df, df2], axis=1) #행(column)을 기준으로 합칠때는 axis=1로 옵션을 부여합니다 -> 가로로 붙여준거

이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수    이름    연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260    지민  3000    3
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  지드래곤  3500    3
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  강다니엘  3200    4
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501     뷔  3050    4
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928    화사  4300    3
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335    정국  2900    5
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792    민현  3400    6
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615    소연  4500    5
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308     진  4200    4
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489   하성운  4300    4
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661    태연  3700    3
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027   차은우  3850    5
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654    백호  3900    4
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137    JR  4100    3
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442    슈가  4150    3

이론 ppt로!

In [ ]:
#merge()
## 교집합(inner)로 병합하기->모두 키값이 존재하는 경우만 병합합니다.
###여기서 키값은 이름으로 정해줬어요-> on 
import pandas as pd
pd.merge(df, df2, on='이름', how='inner')

이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수    연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260  3000    3
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  3500    3
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  3200    4
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501  3050    4
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928  4300    3
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335  2900    5
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792  3400    6
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615  4500    5
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308  4200    4
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489  4300    4
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661  3700    3
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027  3850    5
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654  3900    4
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137  4100    3
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442  4150    3

In [ ]:
#합집합(outer)로 병합하기
###outer 방식은 키값이 존재하면 모두 병합해요
pd.merge(df, df2, on='이름', how='outer')

이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수    연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260  3000    3
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  3500    3
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  3200    4
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501  3050    4
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928  4300    3
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335  2900    5
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792  3400    6
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615  4500    5
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308  4200    4
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489  4300    4
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661  3700    3
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027  3850    5
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654  3900    4
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137  4100    3
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442  4150    3

In [ ]:
pd.merge(df, df2, on='이름', how='left')

이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수    연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260  3000    3
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  3500    3
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  3200    4
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501  3050    4
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928  4300    3
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335  2900    5
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792  3400    6
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615  4500    5
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308  4200    4
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489  4300    4
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661  3700    3
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027  3850    5
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654  3900    4
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137  4100    3
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442  4150    3

In [ ]:
pd.merge(df, df2, on='이름', how='right')

이름     그룹      소속사  성별        생년월일      키 혈액형   브랜드평판지수    연봉  가족수
0     지민  방탄소년단      빅히트  남자  1995-10-13  173.6   A  10523260  3000    3
1   지드래곤     빅뱅       YG  남자  1988-08-18  177.0   A   9916947  3500    3
2   강다니엘    NaN      커넥트  남자  1996-12-10  180.0   A   8273745  3200    4
3      뷔  방탄소년단      빅히트  남자  1995-12-30  178.0  AB   8073501  3050    4
4     화사    마마무      RBW  여자  1995-07-23  162.1   A   7650928  4300    3
5     정국  방탄소년단      빅히트  남자  1997-09-01  178.0   A   5208335  2900    5
6     민현   뉴이스트     플레디스  남자  1995-08-09  182.3   O   4989792  3400    6
7     소연    아이들       큐브  여자  1998-08-26    NaN   B   4668615  4500    5
8      진  방탄소년단      빅히트  남자  1992-12-04  179.2   O   4570308  4200    4
9    하성운     핫샷  스타크루이엔티  남자  1994-03-22  167.1   A   4036489  4300    4
10    태연   소녀시대       SM  여자  1989-03-09    NaN   A   3918661  3700    3
11   차은우   아스트로     판타지오  남자  1997-03-30  183.0   B   3506027  3850    5
12    백호   뉴이스트     플레디스  남자  1995-07-21  175.0  AB   3301654  3900    4
13    JR   뉴이스트     플레디스  남자  1995-06-08  176.0   O   3274137  4100    3
14    슈가  방탄소년단      빅히트  남자  1993-03-09  174.0   O   2925442  4150    3

해결이 어려운 경우 구글링 또는 앞에서 공부한 내용을 참고하셔도 좋습니다.

In [ ]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df = pd.DataFrame(data)
df

영화  개봉 연도  관객 수    평점
0         명량   2014  1761  8.88
1       극한직업   2019  1626  9.20
2  신과함께-죄와 벌   2017  1441  8.73
3       국제시장   2014  1426  9.16
4         괴물   2006  1301  8.62
5        도둑들   2012  1298  7.64
6    7번방의 선물   2013  1281  8.83
7         암살   2015  1270  9.10

In [ ]:
#미션9 전체 데이터 중에서 '영화' 정보만 출력하시오.
df['영화']

0           명량
1         극한직업
2    신과함께-죄와 벌
3         국제시장
4           괴물
5          도둑들
6      7번방의 선물
7           암살
Name: 영화, dtype: object

.

In [ ]:
#미션10 전체 데이터 중에서 '영화', '평점' 정보를 출력하시오
df[['영화','평점']]

영화    평점
0         명량  8.88
1       극한직업  9.20
2  신과함께-죄와 벌  8.73
3       국제시장  9.16
4         괴물  8.62
5        도둑들  7.64
6    7번방의 선물  8.83
7         암살  9.10

In [ ]:
#미션11 2015년 이후에 개봉한 영화 데이터 중에서 '영화', '개봉 연도' 정보를 출력하시오.
df.loc[df['개봉 연도'] >= 2015, ['영화','개봉 연도']]

영화  개봉 연도
1       극한직업   2019
2  신과함께-죄와 벌   2017
7         암살   2015

In [ ]:
#미션12 주어진 계산식을 참고하여 '추천 점수' Column 을 추가하시오.
##> 추천 점수 = (관객수 * 평점) // 100
###예) 첫 번째 영화인 '명량'의 경우,

#추천 점수 = (1761 *8.88) // 100 
df['추천 점수'] = (df['관객 수']*df['평점']) // 100

In [ ]:
df

영화  개봉 연도  관객 수    평점  추천 점수
0         명량   2014  1761  8.88  156.0
1       극한직업   2019  1626  9.20  149.0
2  신과함께-죄와 벌   2017  1441  8.73  125.0
3       국제시장   2014  1426  9.16  130.0
4         괴물   2006  1301  8.62  112.0
5        도둑들   2012  1298  7.64   99.0
6    7번방의 선물   2013  1281  8.83  113.0
7         암살   2015  1270  9.10  115.0

In [ ]:
import pandas as pd

In [ ]:
#미션13 전체 데이터를 '개봉 연도' 기준 내림차순으로 출력하시오.
df.sort_values('개봉 연도', ascending= False)

영화  개봉 연도  관객 수    평점  추천 점수
1       극한직업   2019  1626  9.20  149.0
2  신과함께-죄와 벌   2017  1441  8.73  125.0
7         암살   2015  1270  9.10  115.0
0         명량   2014  1761  8.88  156.0
3       국제시장   2014  1426  9.16  130.0
6    7번방의 선물   2013  1281  8.83  113.0
5        도둑들   2012  1298  7.64   99.0
4         괴물   2006  1301  8.62  112.0